"""2

Revision ID: 34efb1c15bed
Revises: 0c9fe411390c
Create Date: 2020-12-22 11:41:49.193611

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '34efb1c15bed'
down_revision = '0c9fe411390c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('premises_notifications',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('to_user', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('from_user', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('received', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('premises', postgresql.UUID(as_uuid=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_premises_notifications_id'), 'premises_notifications', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_premises_notifications_id'), table_name='premises_notifications')
    op.drop_table('premises_notifications')
    # ### end Alembic commands ###
