"""2

Revision ID: 3fda9cc1bc40
Revises: 3e82be4aa67e
Create Date: 2020-12-24 16:33:07.805389

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3fda9cc1bc40'
down_revision = '3e82be4aa67e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_info', sa.Column('cellphone', sa.String(), nullable=True))
    op.drop_column('user_info', 'phone')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_info', sa.Column('phone', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('user_info', 'cellphone')
    # ### end Alembic commands ###
